name: "CI"
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout mysql-tester
        uses: actions/checkout@v4
      - name: checkout TiDB
        uses: actions/checkout@v4
      - name: Move TiDB
         run: mv tidb ../
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: vet
        run: go vet ./...
      - name: build
        run: make build
      - name: test
        run: make test
