name: "CI"
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install mysql-server to get perror
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server 
      - name: checkout mysql-tester
        uses: actions/checkout@v4
      - name: checkout TiDB
        uses: actions/checkout@v4
        with:
          repository: pingcap/tidb
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: vet
        run: go vet ./...
      - name: build
        run: make build
      - name: test
        run: make test
